#include<iostream>
using namespace std;

main()
{
    	cout<<"I am Tamjeed Dhib"<<endl;
	cout<<"En_no:-220130318041 "<<endl;
	cout<<"._.._.._.._.._.._.._.._.._."<<endl;

	cout<<"The Size of Integer data type is    ::"<<sizeof(int)<<" bytes "<<endl;
	cout<<"The Size of Float data type is      ::"<<sizeof(float)<<" bytes "<<endl;
	cout<<"The Size of Character  data type is ::"<<sizeof(char)<<" bytes "<<endl;
	cout<<"The Size of Double data type is     ::"<<sizeof(double)<<" bytes "<<endl;
	
	return 0;
	
}